### ISSUE TITLE
Opportunities should have a type

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#15]
In order to allow for people to find the opportunities best catered to their abilities, some types:

+ documentation
+ feature
+ bug
+ discussion
+ translation

**Comment by ybur-yug** [comment]
This works great if people in the repos we are concerned with use standard tags, but what if they dont? Manual classification by someone? Just not list them?

**Comment by doomspork** [comment]
They won't have a type and will be more difficult to filter and search for.  Projects that want to participate in this endeavor will need to conform to a standard set of labels that makes it easier for us and contributors to deduce what is what.

One of the chief complaints that I keep hearing is it's difficult to know what issues are in need of being tackle and which are noise, require labels is one way of us filtering the noise out.  If it isn't labeled then it hasn't been triaged by a maintainer.

**Comment by doomspork** [comment]
Now that #14 is merged this is up for grabs.  We should probably discuss what labels we're going to map over before we dive into this too much.

**Comment by doomspork** [comment]
@ybur-yug / @burden / @ponty96 what do you think about initially supporting these categories:

+ Bug
+ Feature
+ Enhancement
+ Documentation

These seem to be the most common.  Projects like Elixir also have "Chores" but I don't see many other projects with them, we could map those to something like "Feature" if necessary.

**Comment by ybur-yug** [comment]
👍 by me, sounds like a reasonable start and we can respond to maintainers from there per their needs since we are ultimately trying to help them @doomspork
