### ISSUE TITLE
The list of opportunities should support pagination

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#19]
We currently fetch all available opportunities and their associated projects, this certainly won't scale.  To accomplish this we should implement basic pagination.

- [ ] UI Changes
- [ ] API Changes (#25)

**Comment by ybur-yug** [comment]
I can take this one tonight and drop in scrivener if you want @doomspork

**Comment by m13m** [comment]
I want work on this.

**Comment by ybur-yug** [comment]
@m13m myself and @sliu27 are currently working on this feature right now, but there is a lot more to do as well. I will ping you in the PR when we open it here in a moment.

**Comment by doomspork** [comment]
@m13m would you be interested in working on #22 or #23?

**Comment by m13m** [comment]
that would be cool yes I'm interested working on #22

**Comment by doomspork** [comment]
@m13m take a peek at what @ybur-yug and @sliu27 are doing with #25 and you should be able to get started.  If you want to fork and get a branch up, we can continue the discussion in #22 👍

**Comment by doomspork** [comment]
@m13m we're also available in Elixir Slack's #elixirschool channel 😀

**Comment by doomspork** [comment]
Re-opening for the UI portion.

**Comment by burden** [comment]
Working on this. PR to follow shortly.
