### ISSUE TITLE
The list of opportunities should be sortable

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#22]
We need to update `Data.Opportunities.all/0` to allow us to sort by any field on the schema.

- [ ] UI Changes
- [x] API Changes

**Comment by dberget** [comment]
#28 is currently in progress for this issue.

**Comment by doomspork** [comment]
I marked that API changes as completed, thanks again for getting involved @dberget!  I hope you'll stick around and help us build something great 😀

**Comment by dberget** [comment]
@doomspork To perform sorting on the UI side, is it best to pattern match on the params for each sortable option like this? 

` def index(conn, %{"sort_by" => "title"} = params) do
    results = Opportunities.all(%{include: :project, sort_by: :title})
    render(conn, "opportunities.html", results: results)
  end
`
