### ISSUE TITLE
Opportunities should be accessible on a webpage

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#3]
In addition to promoting contributions via Twitter we should make a page available to give people the ability to quickly sort through all available opportunities.

**Comment by doomspork** [comment]
@burden is hacking on this AFAIK 👍

**Comment by burden** [comment]
<img width="1138" alt="screen shot 2017-08-23 at 4 01 51 am" src="https://user-images.githubusercontent.com/73517/29612854-31085bf6-87b8-11e7-8dd9-b71c29fdd0b1.png">
