### ISSUE TITLE
Sorting opportunities by difficult should present them as Starter, Intermediate, and Advanced

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#30]
Once #28 is merged we will have sorting functionality built in 🎉 !  

However, we should look to improve how we sort difficulty.  The code currently sorts the by the actual string value which results in an order of "Advanced", "Intermediate", "Starter".   

What we want when we order by `:difficulty` is: "Starter", "Intermediate", "Advanced".

**Comment by jeffweiss** [comment]
I'd like to suggest we stop using "Starter", "Intermediate", and "Advanced" as our _internal_ representation for difficulty level, and here's why:
 * It makes sorting more difficult
 * It makes i18n more difficult

Given the large number of translations for Elixir School, it makes sense to _start_ thinking about it now.

If we change the internal representation of "Starter", "Intermediate", and "Advanced" to something more sortable like an integer, or at worst, `level_1`, `level_5`, `level_9`, then we easily and quickly sort. When it comes time for user display (Phoenix, Twitter bot), it's fairly easy to incorporate gettext. 

We can still use "Starter", "Intermediate", and "Advanced" on the edges, it's just internal that we use something else. We already attempt to translate the incoming labels to something.

```
Webhook   %{ label: "Level:Starter" }
   |
process_issue
   | 
Opportunity %{level: 1}
```

```
Opportunity %{level: 1}
   |
View
   |
gettext(:en)
   |
Difficulty: Starter
```

```
Opportunity %{level: 1}
   |
View
   |
gettext(:de)
   |
Schwierigkeit: Leicht
```

**Comment by doomspork** [comment]
This is an awesome idea @jeffweiss!  Would you like to take a stab at it?  I would be happy to tweet this out if you're looking to help someone else work through it.  Whichever you prefer 😁
