### ISSUE TITLE
Webhook integration should require a token

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#33]
We don't want people to spam our webhook which can be easily deduced from the code and project URL.  When we onboard a project (manually for now), we should generate a token to be used in the webhook for identification.

Something like this could work: 

```
/webhooks/github?access_token=
```

**Comment by jeffweiss** [comment]
I have a handful of questions for things that have not yet been specified.

* Where do we intend to store these tokens? Database? Memory? [Vault](https://www.vaultproject.io/)?
* Is a token per user or per repo?
* Are we going to validate that token provided was actually issued to the person/project contained in the webhook?
* What if we need to roll the tokens?

**Comment by doomspork** [comment]
Great questions @jeffweiss 😀 

+ The database for the time being.  The PR #36 includes a `api_token` field that would be generated when the project is created.
+ Per repo for now.  There is no concept of user in the MVP.
+ We should!  I can take a crack at that with #36 
+ By roll you mean reset?  We can write a new token to the DB and the deed is done.
