### ISSUE TITLE
GitHub Scheduler should occasionally sync with the database

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#43]
As it stands the only time the GitHub Scheduler syncs it's projects with the database is on app start-up.  We should occasionally check with the database and sync our state instead.

**Comment by treble37** [comment]
I'd like to take a crack at this one if you don't mind.... :) - I have 2 questions if you'd like:

1) for what you define as "occasionally" for syncing the state and database - how about 24 hours?
2) Is it correct to say new Projects are chosen by "humans" and defined in `apps/data/priv/repo/seeds.exs`?  Just trying to understand

**Comment by doomspork** [comment]
@treble37 I started on this last night but I'd be more than happy to have you take this and finish it 👍 

1) I think 12 or 24 hours is sufficient 👍 
2) Right now projects are manually added to the database in production, the seed.exs is only for dev.  There's some features coming down the pipe that will allow someone to sign-up for an account and enable their GitHub repos (which will apply the webhook).

Let me know if you have any questions @treble37 👍

**Comment by treble37** [comment]
Assuming this code adds the correct functionality, should I test it?
