### ISSUE TITLE
Refactor pagination CSS to use mobile-first approach

### ISSUE THREAD

**Issue by sobering** [elixirschool/extracurricular#53]
The new Extracurricular UI takes a mobile-first approach to it's CSS architecture, meaning all default styles (CSS _not_ in a media query) are the mobile styles, and anything inside a media query are the styles for larger devices. This is beneficial because mobile device browsers won't have to parse anything inside a media query.

The pagination component, however, does not take a mobile-first approach. To resolve this Issue, the pagination media query should be inverted, and styles adjusted accordingly.

**Comment by ppsmirnov** [comment]
Can i take this one?

**Comment by doomspork** [comment]
Go for it @ppsmirnov!  Thank you for getting involved 👍

**Comment by treble37** [comment]
Perhaps this issue can be closed since the related PR was merged @doomspork ?

**Comment by doomspork** [comment]
Good catch @treble37 — sorry about that 👍
