### ISSUE TITLE
Listed issues should not contain Pull Requests

### ISSUE THREAD

**Issue by rhnonose** [elixirschool/extracurricular#62]
The listed issues contains Pull Requests as well.
As per [github's API](https://developer.github.com/v3/issues/), PRs are closely similar to issues hence the reason it also returns PRs.
I believe the listing should only contain issues or, if PRs could be listed as well, should contain a tag specifying it's a PR.

**Comment by doomspork** [comment]
@rhnonose good catch!  We should filter those out 👍
