### ISSUE TITLE
Incorporate React Router into the front-end application

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#63]
We are currently rebuilding the UI on [feature/react-redux-spa](https://github.com/elixirschool/extracurricular/tree/feature/react-redux-spa) to use React.  We should include the React Router so we can begin to add additional pages to the site.

cc @cafreeman

**Comment by Akin909** [comment]
Hey I can have a look at adding this, is there a contributing.md or general rules e.g. formatting of the JS etc, shall I branch off of feature/react-redux-spa and make a pr into that branch?

**Comment by Akin909** [comment]
I've added react router locally, I can make a pr into your feature/react-redux-spa branch for you to review if you'd like

**Comment by doomspork** [comment]
@Akin909 I'm not personally a JS dev so I don't have a strong feeling about JS at this point in time.  Feel free to open a PR against the `feature/react-redux-spa` branch!

If you're participating in Hacktoberfest, I will have to defer merging the PR until after Oct 1 😀

**Comment by Akin909** [comment]
@doomspork Thanks (re. Hacktoberfest I am participating). I can't push my branch to this repo though as I don't have access rights

**Comment by doomspork** [comment]
Closed by @Akin909 in #67
