### ISSUE TITLE
The React application should update the browser history

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#64]
As part of the rebuilding efforts taking place on [feature/react-redux-spa](https://github.com/elixirschool/extracurricular/tree/feature/react-redux-spa), we should ensure the browser's history is updated.

**Comment by tleskin** [comment]
I'd like to take a shot at this if that's alright. What are you looking for it to do/look like exactly?

**Comment by doomspork** [comment]
@tleskin we just need to update the browser history when a user changes the filters.  Open to thoughts and ideas 😀
