### ISSUE TITLE
Periodically tweet call to actions

### ISSUE THREAD

**Issue by doomspork** [elixirschool/extracurricular#9]
On some sort of schedule we should tweet different calls to action:

+ How many overall contributions are available
+ Particular repos and the number of issues

As we gather analytics we could additionally tweet:

+ Which repos are very action
+ Which repos need attention

There's a lot of room for discussion here, what are we thinking?

**Comment by ybur-yug** [comment]
I think there could be an alternative approach with the goals of this. We want to alert people for opportunities to contribute in multiple areas as well as with multiple amounts of complexity.

What if we made a family of bots that segmented this in a way that made individualized feeds people could subscribe to that fit their needs and where they were at?

We could have one for overall documentation, one for beginner stuff and low hanging fruit, and one for larger more advanced gigs. We could also have one that shares articles and links that might end up being in the newsletter to get more subscribers involved etc.

I think by segmenting this out into more fine-grained spickets for people to follow would help engagement and lower the  signals-to-noise ratio.

Thoughts?

**Comment by doomspork** [comment]
I'm not thrilled about the idea of having multiple twitter accounts and bots all tweeting a filtered set.  If I subscribe to the beginner bot and grow as a developer I need to unfollow one bot and follow a new one, this seems like a hurdle rather than a feature.  Furthermore, we risk having accounts sit dormant because there simplify aren't issues for those.  If we get to the point that we're making 1000 tweets a day it may make sense to look at how to decrease the noise but for now it seems like a premature optimization that introduces complexity.

The point of the tweets is to call attention to certain issues (those projects that are 100% committed to our labels etc) and general calls to action "We've seen 100 new opportunities this week, looking to get involved?  Check them out at .....".

The most important thing we can do at this particular moment is focus on getting out the MVP and validating people like the idea.  I'm afraid if we start to tack too much we're not going to see the project launch.

**Comment by doomspork** [comment]
Copying this over from @ybur-yug's comments elsewhere:

## Implementation
- [ ] tweet how many opportunities overall are available and projects + their counts of opportunities individually
  - [ ] make an opportunity (issue) belong to a project (github repo)
  - [ ] set up client that exposes interface to all opportunities
      - [ ] set up interface in client that exposes a project + its opportunities loaded for CTA tweet
  - [ ] set up scheduler genserver for call to action tweets
- [ ] determine template for tweets
- [ ] determine interval in which to tweet various messages


## Notes
It may be work considering extracting the periodic behaviour of the scheduler right now into its own module that just takes a module/function/arguments and then runs them in the task supervisor like we do in the bot with Github issues now.

I have started the work and got twitters interface exposed and am working on getting the periodic part done after that. Next up will be the schema work, followed by finally figuring out the final copy of the real tweets and then also when to send them out.

**Comment by doomspork** [comment]
Let's hold off on this for now.
